<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NotaDebitoController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:\\xampp\\htdocs\\FactelWebCliente\\app\\cache\\prod/jms_diextra/proxies/FactelBundle-Controller-NotaDebitoController.php';
        $j = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\NotaDebitoController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'notasDebitoAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'sendEmail' => array(0 => 'security.access.method_interceptor'), 'procesarAccion' => array(0 => 'security.access.method_interceptor'), 'descargarAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyb8ed51cf_eb81e5486c3da4dc3a29a367a418894466ac68da\__CG__\FactelBundle\Controller\NotaDebitoController();
        $instance->__CGInterception__setLoader($j);
        return $instance;
    }
}
