<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EmisorController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:\\xampp\\htdocs\\FactelWebCliente\\app\\cache\\prod/jms_diextra/proxies/FactelBundle-Controller-EmisorController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\EmisorController' => array('createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyb8ed51cf_1e69c734e02628c4047dd20339d80fc0a6a24ecd\__CG__\FactelBundle\Controller\EmisorController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
