<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class NotaCreditoController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:\\xampp\\htdocs\\FactelWebCliente\\app\\cache\\prod/jms_diextra/proxies/FactelBundle-Controller-NotaCreditoController.php';
        $i = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\NotaCreditoController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'notasCreditoAction' => array(0 => 'security.access.method_interceptor'), 'procesarAccion' => array(0 => 'security.access.method_interceptor'), 'sendEmail' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'descargarAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyb8ed51cf_6df9ec566adbe3b33ecad76c1c59b1fd2c3567a9\__CG__\FactelBundle\Controller\NotaCreditoController();
        $instance->__CGInterception__setLoader($i);
        return $instance;
    }
}
