<?php

namespace FactelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FacturaController__JMSInjector
{
    public static function inject($container) {
        require_once 'C:\\xampp\\htdocs\\FactelWebCliente\\app\\cache\\prod/jms_diextra/proxies/FactelBundle-Controller-FacturaController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('FactelBundle\\Controller\\FacturaController' => array('facturasAction' => array(0 => 'security.access.method_interceptor'), 'procesarAccion' => array(0 => 'security.access.method_interceptor'), 'sendEmail' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'descargarAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'showAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'deleteAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxyb8ed51cf_18a53ef5491c778a5a5049cdb7db7fd638e8f30d\__CG__\FactelBundle\Controller\FacturaController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
